### ISSUE TITLE
 How to use your algorithm in static images

### ISSUE THREAD

**Issue by jianghongsun** [mahaveerverma/hand-gesture-recognition-opencv#9]
Thank you very much for your algorithm.Can you give me some advice for me in static images？

**Comment by mahaveerverma** [comment]
@jianghongsun The code will wait for you to capture background, then to capture hand and then it will proceed with capturing video frames in realtime. This code was written keeping video in mind and here we have the luxury of first capturing a blank background and hand histogram in pre-processing stage to not just help recoginition in the later stages but also as a method to understand the difference between hand in the foreground and the remaining background. I doubt the same framework will be useful to you in static images but you can try removing the part where background comes into picture (in processing mainly, it's okay if you mess up the capturing part but you need to properly remove the part where background is being used in processing) and then try detecting hand based on just a sample histogram instead of a histogram captured live (in video, for this code). I'm closing this 'issue' since it's not really an issue. Feel free to email me at mahaveer.verma1@gmail.com if you need further assistance.

**Comment by jianghongsun** [comment]
Thank you for you reply.If I have some problem,I will trouble you. 





------------------ 原始邮件 ------------------
发件人: "Mahaveer Verma"<notifications@github.com>;
发送时间: 2018年3月30日(星期五) 晚上10:27
收件人: "mahaveerverma/hand-gesture-recognition-opencv"<hand-gesture-recognition-opencv@noreply.github.com>;
抄送: "孙江宏"<1456098533@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [mahaveerverma/hand-gesture-recognition-opencv] How to use youralgorithm in static images (#9)




@jianghongsun The code will wait for you to capture background, then to capture hand and then it will proceed with capturing video frames in realtime. This code was written keeping video in mind and here we have the luxury of first capturing a blank background and hand histogram in pre-processing stage to not just help recoginition in the later stages but also as a method to understand the difference between hand in the foreground and the remaining background. I doubt the same framework will be useful to you in static images but you can try removing the part where background comes into picture (in processing mainly, it's okay if you mess up the capturing part but you need to properly remove the part where background is being used in processing) and then try detecting hand based on just a sample histogram instead of a histogram captured live (in video, for this code). I'm closing this 'issue' since it's not really an issue. Feel free to email me at mahaveer.verma1@gmail.com if you need further assistance.
